name: Lint

on:
- push
- pull_request

jobs:
  lint:
    name: Run Lint Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "🐍 Set up Python"
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install tox
        run: python -m pip install tox
      - name: Run lint checks with tox
        run: tox -e check
